sudo: false
language: java
cache:
  directories:
    - "$HOME/.cache"
jdk:
  - openjdk8

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - someone@fromproject.com
    on_success: change
    on_failure: always

##  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V